---
title: "COVID-19"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    source_code: https://github.com/labbcb/covid19unicamp
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
source("data_functions.R")
source("plot_functions.R")

data <- load_data()
data_state <- get_data_state(data)
data_city <- get_data_city(data)
map_data <- calc_map_data(data)

if (file.exists("dados_municipios.rds")) {
  require(geobr)
  dados_municipios <- readRDS("dados_municipios.rds")
} else {
  dados_municipios = read_municipality(code_muni="SP", year=2018, showProgress = FALSE)
  saveRDS(dados_municipios, "dados_municipios.rds")
}
dyn_map_data = get_data_munic_from_state(data, "SP", dados_municipios)
```

Campinas {data-icon="fa-street-view"}
=====================================

Row
-------------------------------------

### Confirmados {.value-box}

```{r}
renderValueBox({
  valueBox(last(data_city$confirmed),
           icon = "fa-plus-square",
           color = "orange")
})
```

### Óbitos {.value-box}

```{r}
renderValueBox({
  valueBox(last(data_city$deaths),
           icon = "fa-procedures",
           color = "red")
})
```

### CFR Campinas

```{r}
cfrWHO = 3.4

getCFR = function(input){
  input %>% ungroup() %>% arrange(date) %>% tail(n=1) %>% 
    mutate(CFR=round(deaths/confirmed * 100, 2)) %>% pull()
}

my_sectors = gaugeSectors(success=c(0, cfrWHO),
                        warning = c(cfrWHO+0.01, 2*cfrWHO),
                        danger = c(2*cfrWHO + 0.01, 100))

gauge(data_city %>% getCFR(), min=0,
      max=100, symbol="%", my_sectors)
```


### CFR Estado de SP

```{r}
gauge(data_state %>% getCFR(), min=0, max=100, symbol="%",
      my_sectors)
```

### CFR Brasil

```{r}
brasilCFR = data %>%
  filter(place_type == "state", is_last) %>%
  select(confirmed, deaths) %>%
  summarise(CFR=round(sum(deaths)/sum(confirmed)*100, 2)) %>% 
  pull()
gauge(brasilCFR, min=0, max=100, symbol="%",
      my_sectors)
```


Row
-------------------------------------

### Casos e Óbitos até a Presente Data

```{r}
plot_cumulative_cases(data_city)
```

### Casos Diários

```{r}
plot_daily_cases(data_city)
```

Estado de Sao Paulo {data-icon="fa-city"}
=====================================

Row
-------------------------------------

### Confirmados {.value-box}

```{r}
renderValueBox({
  valueBox(last(data_state$confirmed),
           icon = "fa-plus-square",
           color = "orange")
})
```

### Óbitos {.value-box}

```{r}
renderValueBox({
  valueBox(last(data_state$deaths),
           icon = "fa-procedures",
           color = "red")
})
```

Row
-------------------------------------

### Casos e Óbitos até a Presente Data

```{r}
plot_cumulative_cases(data_state)
```

### Casos Diários

```{r}
plot_daily_cases(data_state)
```

Brasil {data-icon="fa-globe-americas"}
=====================================

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
radioButtons(
  "mapBrChoice",
  "Métrica:",
  c(
    "Casos Confirmados" = "confirmed1m",
    "Óbitos" = "deaths1m",
    "CFR" = "CFR"
  )
)
```

Column
-----------------------------------------------------------------------

### Mapa

```{r}
renderPlot({
  plot_brazil_map(map_data, input$mapBrChoice)
})
```

Mapas (Fase: alpha) {data-icon="fa-map-marked-alt"}
=====================================

```{r}
renderLeaflet({
   create_dyn_map(dyn_map_data, "confirmed_per_100k_inhabitants") 
})
```

